apiVersion: k8sservice/v1alpha1
kind: GetService
metadata:
  name: single-service
spec:
  regex: true
  matchStr: "vela"
  getAll: false
  namespaces:
  - vela-system
  - default
  deployment:
    name: single-service
    labelSelector:
      app: single-service

