---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8sservice-example-cn-v1alpha1-getservice
  failurePolicy: Fail
  name: mgetservice-v1alpha1.kb.io
  rules:
  - apiGroups:
    - k8sservice.example.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - getservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8sservice-example-cn-v1alpha1-getservice
  failurePolicy: Fail
  name: vgetservice-v1alpha1.kb.io
  rules:
  - apiGroups:
    - k8sservice.example.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - getservices
  sideEffects: None
