server:
  listen:
    host: "0.0.0.0"
    port: "8080"
  # api_key: "QPZXkYDY2cXG1vRKfIpwdqzBOpf4G1Zy"

  # TODO: log rotation
  log:
    level: "debug"
    error_path: "./logs/error.log"
    access_path: "./logs/access.log"
    max_size: 100
    max_age: 30
    max_backups: 3
    compress: true
    local_time: true
    json: true

  # prometheus:
    # enabled: false
    # path: "/metrics"

  # sentry:
    # enabled: false
  
  jwt:
    secret: "secret" # Not used
    expired: 3600 # seconds
    
  cors:
    enabled: false
    allow_origins: "*"
    allow_methods: "GET,POST,PUT,DELETE"
    allow_headers: "Content-Type,Authorization"
    expose_headers: "Content-Type,Authorization"
    allow_credentials: false
    max_age: 0

  fiber_config:
    app_name: "demo-base"
    body_limit: 409600
    concurrent: 1000
    network: "tcp"
    prefork: false
    read_buffer_size: 4096
    read_timeout: 5000
    write_buffer_size: 4096
    write_timeout: 30000
    idle_timeout: 120
  
database:
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "Denglu%0416"
    db: "demo_base"
    max_idle_connections: 10
    max_open_connections: 100
    max_life_time: 600 # 秒
    max_idle_time: 300 # 秒
  # etcd, used to store etcd watcher for casbin
  etcd:
    endpoints:
    - "127.0.0.1:2379"
    - "127.0.0.1:2380" # 带端口，多个用分号（;）隔开
    username: ""
    password: ""
    dial_timeout: 5 # 秒
    skip_tls: true
    cert_file: "./certs/etcd.crt"
    key_file: "./certs/etcd.key"
    ca_file: "./certs/ca.crt"
    prefix: "/demo_base"

  # redis:

  # etcd:
  