---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8sservice.example.cn
  resources:
  - getservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8sservice.example.cn
  resources:
  - getservices/finalizers
  verbs:
  - update
- apiGroups:
  - k8sservice.example.cn
  resources:
  - getservices/status
  verbs:
  - get
  - patch
  - update
