apiVersion: k8sservice.example.cn/v1alpha1
kind: GetService
metadata:
  labels:
    app.kubernetes.io/name: k8ssvc-crd
    app.kubernetes.io/managed-by: kustomize
  name: sample
  namespace: test
spec:
  # TODO(user): Add fields here
  namespace: kube-system
