apiVersion: k8sservice.example.cn/v1alpha1
kind: GetService
metadata:
  labels:
    app.kubernetes.io/name: k8sservice-crd
    app.kubernetes.io/managed-by: kustomize
  name: getservice-sample
  annotations:
    app.k8s.io/namespace: default
spec:
  # TODO(user): Add fields here
